version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: challenge-itrock-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: taskdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: challenge-itrock-app
    restart: always
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/taskdb
      JWT_SECRET: supersecreto
      API_KEY: supersecreta
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
      - /app/node_modules
    command: ["sh", "-c", "sleep 5 && npm start"]

volumes:
  mongo_data:
